name: Build and Deploy Microservices

on:
  push:
    branches:
      - main

jobs:
  determine_services:
    name: Determine changed services
    runs-on: ubuntu-latest
    outputs:
      changed_services: ${{ steps.changed_services.outputs.json }}

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get list of changed files
        id: git_changes
        run: |
          echo "Determining changed files..."
          CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD | tr '\n' ' ')
          echo "Changed files: $CHANGED_FILES"
          echo "::set-output name=changed_files::$CHANGED_FILES"

      - name: Determine changed services
        id: changed_services
        run: |
          echo "Evaluating changed services..."
          services=()
          for path in ${{ steps.git_changes.outputs.changed_files }}; do
            if [[ $path == Microservices/* ]]; then
              service=$(echo "$path" | cut -d'/' -f2)
              if [[ ! " ${services[*]} " =~ " ${service} " ]]; then
                services+=("$service")
              fi
            fi
          done

          # Check if any services found
          if [ ${#services[@]} -eq 0 ]; then
            echo "No changed services detected. Exiting with error."
            exit 1
          fi

          # Convert to JSON array
          json=$(printf '%s\n' "${services[@]}" | jq -R . | jq -s .)
          echo "Resulting JSON: $json"
          echo "::set-output name=json::$json"


  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    needs: determine_services
    strategy:
      matrix:
        service: ${{ fromJson(needs.determine_services.outputs.changed_services) }}

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up JDK 21 with Corretto
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Grant execute permissions for gradlew
        run: chmod +x Microservices/${{ matrix.service }}/gradlew

      - name: Build with Gradle
        working-directory: Microservices/${{ matrix.service }}
        run: ./gradlew clean build

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./Microservices/${{ matrix.service }}
          file: ./Microservices/${{ matrix.service }}/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}-${{ matrix.service }}:latest